server:
  port: 8082

spring:
  application:
    name: log-monitor-backend
  output:
    ansi:
      enabled: always

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

# logging:
#   level:
#     root: OFF
