filebeat.inputs:
  - type: filestream
    id: logs-app-filestream-id
    enabled: true
    paths:
      - /var/log/logs-app/system.log
    scan_frequency: 1s
    backoff.init: 1s
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          expand_keys: true

processors:
  - add_fields:
      target: ""
      fields:
        environment: "staging"
        app: "logs-app"
        service: "logs-service"

output.logstash:
  hosts: ["54.255.209.190:5044"]
  flush.timeout: 1s
