input {
  beats {
    port => 5044
  }
}

filter {
  if ![level] {
    mutate {
      add_field => { "level" => "UNKNOWN" }
    }
  }

  if ![app] {
    mutate {
      add_field => { "app" => "logs-app" }
    }
  }

  if ![environment] {
    mutate {
      add_field => { "environment" => "staging" }
    }
  }

  mutate {
    rename => {
      "traceId" => "trace_id"
      "logger_name" => "logger"
      "thread_name" => "thread"
      "message" => "main_message"
    }
    add_field => {
      "host_name" => "%{[host][name]}"
      "log_timestamp" => "%{@timestamp}"
    }
  }

  if ![trace_id] or [trace_id] == "" {
    uuid {
      target => "trace_id"
    }
  }

  uuid {
    target => "doc_id"
  }

  mutate {
    remove_field => [
      "agent",
      "ecs",
      "event",
      "host",
      "input",
      "log",
      "LOG_FILE",
      "level_value",
      "tags",
      "@version"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://log-monitor-elasticsearch:9200"]
    index => "sys-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}