input {
  beats {
    port => 5044
  }
}

# =============================================================
filter {

  grok {
    match => {
      "message" => [

        '(?m)^%{TIMESTAMP_ISO8601:log_timestamp}\s+\[%{DATA:thread}\]\s+\[%{DATA:trace_id}\]\s+%{LOGLEVEL:level}\s+%{NOTSPACE:logger}\s+-\s+%{GREEDYDATA:raw_message}',

        '(?m)^%{TIMESTAMP_ISO8601:log_timestamp}\s+\[%{DATA:thread}\]\s+%{LOGLEVEL:level}\s+%{NOTSPACE:logger}\s+-\s+%{GREEDYDATA:raw_message}'
      ]
    }
    tag_on_failure => ["_grokparsefailure"]
  }

  if ![trace_id] or [trace_id] == "" {
    uuid {
      target => "trace_id"
    }

    mutate {
      add_tag => ["no_trace_id"]
    }
  }

  if "_grokparsefailure" not in [tags] {

    date {
      match => ["log_timestamp", "yyyy-MM-dd HH:mm:ss.SSS"]
      target => "@timestamp"
      timezone => "Asia/Ho_Chi_Minh"
      remove_field => ["log_timestamp"]
    }

    #
    # Dòng đầu = message
    # Phần còn lại = stacktrace
    #
    grok {
      match => {
        "raw_message" => "(?m)^(?<main_message>[^\n]+)\n(?<stack_trace>.*)$"
      }
      tag_on_failure => []
    }

    #
    # Không có stacktrace
    #
    if ![main_message] {
      mutate {
        add_field => {
          "main_message" => "%{raw_message}"
        }
      }
    }

  }

  mutate {

    add_field => {
      "host_name" => "%{[host][name]}"
    }

    strip => [
      "level",
      "logger",
      "thread"
    ]

    remove_field => [
      "agent",
      "ecs",
      "input",
      "log",
      "@version",
      "event",
      "message",
      "raw_message" 
    ]
  }

  uuid {
    target => "doc_id"   # field trong document
  }

}
# =============================================================

output {

  if "_grokparsefailure" not in [tags] {

    elasticsearch {
      hosts => ["http://log-monitor-elasticsearch:9200"]
      index => "sys-logs-%{environment}-%{+YYYY.MM.dd}"
    }

  }
  
  #  if "_grokparsefailure" not in [tags] and [level] in ["ERROR", "WARN"] {
   if "_grokparsefailure" not in [tags] {

    http {

      url         => "http://host.docker.internal:8082/internal/logs/ingest"
      http_method => "post"
      format      => "json"

      mapping => {

        "traceId"        => "%{trace_id}"
        "logLevel"       => "%{level}"
        "environment"    => "%{environment}"
        "serviceName"    => "%{service}"
        "thread"         => "%{thread}"
        "logger"         => "%{logger}"

        "message"        => "%{main_message}"
        "stackTrace"     => "%{stack_trace}"

        "eventTimestamp" => "%{@timestamp}"
        "hostName"       => "%{host_name}"

        
      }

      retryable_codes => [429, 500, 502, 503, 504]
      retry_failed    => false
    }

  }

  stdout {
    codec => rubydebug
  }

}